[workspace]
authors = ["obi <ole.bialas@posteo.de>"]
channels = ["conda-forge"]
name = "iBOTS-Intro-to-EEG-MEG-Analysis-with-MNE-Python"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
register-kernel = "python -m ipykernel install --user --name ibots-eeg-meg"

[dependencies]
python = "3.13.*"

[pypi-dependencies]
ipykernel = ">=7.1.0, <8"
pip = ">=25.3, <26"
mne = ">=1.11.0, <2"
mne-connectivity = ">=0.7.0, <0.8"
ipympl = ">=0.9.8, <0.10"
pyqt5 = ">=5.15.11, <6"
